# @package _global_
data:
  znear: 0.1
  zfar: 10
  fov: 42.44  #51.98948897809546
  category: cars
  white_background: false # this was originally 'true'
  origin_distances: false

model:
  opacity_scale: 0.001
  opacity_bias: -3.0
  scale_scale: 0.001
  scale_bias: 0.02
  xyz_scale: 0.000001
  xyz_bias: 0.0