# @package _global_
data:
  znear: 0.01
  zfar: 5
  fovx: 130.0
  fovy: 103.0
  category: scannetpp
  white_background: false
  origin_distances: true

model:
  opacity_scale: 0.001
  opacity_bias: -3.0
  scale_scale: 0.001
  scale_bias: 0.02
  xyz_scale: 0.000001
  xyz_bias: 0.0